import { create } from "zustand";

const useStore = create((set) => ({
  // data: {},
  name: '',
  changeName: () => set((state) => ({ name: state.name })),
  email: '',
  changeEmail: () => set((state) => ({ email: state.email })),
  phone: '',
  changePhone: () => set((state) => ({ phone: state.phone })),
  website: '',
  changeWebsite: () => set((state) => ({ website: state.website })),
  firstAward: '',
  changeAward: () => set((state) => ({ firstAward: state.firstAward })),
  college: '',
  changeCollege: () => set((state) => ({ college: state.college })),
  collegeLocation: '',
  changeClgLocation: () => set((state) => ({ collegeLocation: state.collegeLocation })),
  degree: '',
  changeDegree: () => set((state) => ({ degree: state.degree })),
  major: '',
  changeMajor: () => set((state) => ({ major: state.major })),
  startDate: '',
  changeSdate: () => set((state) => ({ startDate: state.startDate })),
  endDate: '',
  changeEdate: () => set((state) => ({ endDate: state.endDate })),
  position: '',
  changePosition: () => set((state) => ({ position: state.position })),
  location: '',
  changeLocation: () => set((state) => ({ location: state.location })),
  startPosition: '',
  changeSPosition: () => set((state) => ({ startPosition: state.startPosition })),
  endPosition: '',
  changeEPosition: () => set((state) => ({ endPosition: state.endPosition })),
  address: '',
  changeAddress: () => set((state) => ({ address: state.address })),
  postalCode: '',
  changePostalCode: () => set((state) => ({ postalCode: state.postalCode })),
  city: '',
  changeCity: () => set((state) => ({ city: state.city })),
  region: '',
  changeRegion: () => set((state) => ({ region: state.region })),
  project1 : '',
  changeProject1: () => set((state) => ({ project1: state.project1 })),
  projectDesc1: '',
  changeProjectDesc1: () => set((state) => ({ projectDesc1: state.projectDesc1 })),
  projectTech1: '',
  changeProjectTech1: () => set((state) => ({ projectTech1: state.projectTech1 })),
  project2 : '',
  changeProject2: () => set((state) => ({ project2: state.project2 })),
  projectDesc2: '',
  changeProjectDesc2: () => set((state) => ({ projectDesc2: state.projectDesc2 })),
  projectTech2: '',
  changeProjectTech2: () => set((state) => ({ projectTech2: state.projectTech2 })),
  skills1: '',
  changeSkills1: () => set((state) => ({ skills1: state.skills1 })),
  languages1: '',
  changeLanguages1: () => set((state) => ({ languages1: state.languages1 })),
  skills2: '',
  changeSkills2: () => set((state) => ({ skills2: state.skills2 })),
  languages2: '',
  changeLanguages2: () => set((state) => ({ languages2: state.languages2 })),
}));

export default useStore;
// module.exports = useStore;